/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { GovernaceForward } from "./GovernaceForward";

export { GovernaceForward__factory } from "./factories/GovernaceForward__factory";
